# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections: null

title: "Destination->live"
description: "Quel artiste, groupe, humoriste… tu veux voir ? Fais-le venir près de chez toi !"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://destinationlive.net" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: ["README.md"]

#scss
sass:
  style: compressed
